apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: poke-trainer-ds
spec:
  selector:
    matchLabels:
      name: poke-trainer-ds
  template:
    metadata:
      labels:
        name: poke-trainer-ds
    spec:
      hostNetwork: true
      containers:
      - name: poke-trainer
        image: <acc>.dkr.ecr.us-east-1.amazonaws.com/aaron-poke-ecr:latest
        env:
        - name: NCCL_SOCKET_IFNAME
          value: "eth0"
        # - name: MASTER_ADDR
        #   value: "10.0.1.243"
        # - name: MASTER_PORT
        #   value: "12345"
        ports:
        - containerPort: 12345
          hostPort: 12345
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: 1
      terminationGracePeriodSeconds: 60